create table SYSTEM_PARAM (
    SYS_PARAM_KEY varchar2(20 char) not null,
        SYS_PARAM_VALUE varchar2(20 char) not null,
    primary key (SYS_PARAM_KEY)
);

--COMMENT ON COLUMN "SYSTEM_PARAM"."SYS_PARAM_KEY" IS 'Primary key of SYSTEM_PARAM';
--COMMENT ON COLUMN "SYSTEM_PARAM"."SYS_PARAM_VALUE" IS 'Value';

INSERT INTO SYSTEM_PARAM (SYS_PARAM_KEY, SYS_PARAM_VALUE) values ('IVRS_STATUS_ES1', 'N');
INSERT INTO SYSTEM_PARAM (SYS_PARAM_KEY, SYS_PARAM_VALUE) values ('IVRS_STATUS_ES2', 'Y');