    create table UM_ACCESS_CONTROL_GLOBAL_PARAM (
        AC_PARAM_KEY varchar2(30 char) not null,
		AC_PARAM_VALUE varchar2(256 char) not null,
        primary key (AC_PARAM_KEY)
    )


COMMENT ON COLUMN "UM_ACCESS_CONTROL_GLOBAL_PARAM"."AC_PARAM_KEY" IS 'Primary key of UM_ACCESS_CONTROL_GLOBAL_PARAM';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_GLOBAL_PARAM"."AC_PARAM_VALUE" IS 'Value';

