
  CREATE TABLE UM_APPLICATION_CODE (
  "APP_ID" VARCHAR2(4 BYTE),
	"CREATE_AT" TIMESTAMP (6) DEFAULT SYSDATE,
	"MODIFY_AT" TIMESTAMP (6) DEFAULT SYSDATE,
	"MODIFY_BY" VARCHAR2(1 BYTE),
	"ENG_APP_NAME" VARCHAR2(480 BYTE),
	"CHT_APP_NAME" VARCHAR2(50),
	"CHS_APP_NAME" VARCHAR2(50),
	"REQUIRE_REMINDER" VARCHAR2(1 BYTE) DEFAULT 'N',
	"REMINDER_DAY" NUMBER(3,0),
	"EFFECTIVE_DATE" DATE,
	"UPDATE_FLAG" VARCHAR2(1 BYTE),
	"ACTION_TYPE" VARCHAR2(10 BYTE),
	primary key (APP_ID)
   );

Insert into UM_APPLICATION_CODE (APP_ID,CREATE_AT,MODIFY_AT,MODIFY_BY,ENG_APP_NAME,CHT_APP_NAME,CHS_APP_NAME,REQUIRE_REMINDER,REMINDER_DAY,EFFECTIVE_DATE,UPDATE_FLAG,ACTION_TYPE) values ('640', to_timestamp('18-MAR-15 11.08.50.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-MAR-15 07.28.29.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'W','Application for Entry under the Admission Scheme for the Second Generation of Chinese Hong Kong Permanent Residents','Application','Application','N',0,null,null,null);
Insert into UM_APPLICATION_CODE (APP_ID,CREATE_AT,MODIFY_AT,MODIFY_BY,ENG_APP_NAME,CHT_APP_NAME,CHS_APP_NAME,REQUIRE_REMINDER,REMINDER_DAY,EFFECTIVE_DATE,UPDATE_FLAG,ACTION_TYPE) values ('641', to_timestamp('15-MAR-15 11.08.50.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-MAR-15 07.28.29.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'W','Application for Entry under the Admission Scheme for the Second Generation of Chinese Hong Kong Permanent Residents','Application','Application','N',0,null,null,null);
