create table UM_ACCESS_CONTROL_WHITE_LIST (
	AC_ID NUMBER not null,
	AC_IP varchar2(15 char),
	AC_LIST varchar2(20 char),
	AC_NAME varchar2(50 char),
	CHANNEL varchar2(10 char),
	EFFECT_DATE_FROM timestamp,
	EFFECT_DATE_TO timestamp,
	primary key (AC_ID)
)


COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."APP_ID" IS 'Primary key of UM_ACCESS_CONTROL_WHITE_LIST';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."AC_IP" IS 'IP Address';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."AC_LIST" IS 'Black/White of UM_ACCESS_CONTROL_BLACK_LIST/UM_ACCESS_CONTROL_WHITE_LIST.';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."AC_NAME" IS 'Name';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."CHANNEL" IS 'Channel is IVRS/Web';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."EFFECT_DATE_FROM" IS 'Effective From';
COMMENT ON COLUMN "UM_ACCESS_CONTROL_WHITE_LIST"."EFFECT_DATE_TO" IS 'Effective To';
