--------------------------------------------------------
--  DDL for Table UM_LOCATIONID_OFFICE
--------------------------------------------------------

  CREATE TABLE "UM_LOCATIONID_OFFICE"
   (	"LOCATION_ID" VARCHAR2(10 BYTE), 
	"OFFICE_CODE" VARCHAR2(10 BYTE)
   ) ;
 

  COMMENT ON COLUMN "UM_LOCATIONID_OFFICE"."LOCATION_ID" IS 'Location Id of Mapping in UM_LOCATIONID and UM_OFFICE table';
 
  COMMENT ON COLUMN "UM_LOCATIONID_OFFICE"."OFFICE_CODE" IS 'Office Code of Mapping in UM_LOCATIONID and UM_OFFICE table';

  ALTER TABLE "UM_LOCATIONID_OFFICE" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "UM_LOCATIONID_OFFICE" MODIFY ("OFFICE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "UM_LOCATIONID_OFFICE" ADD CONSTRAINT "UM_LOCATIONID_OFFICE_PK" PRIMARY KEY ("LOCATION_ID", "OFFICE_CODE")
