--------------------------------------------------------
--  DDL for Table UM_LOCATIONID_APP
--------------------------------------------------------

  CREATE TABLE "UM_LOCATIONID_APP"
   (	"LOCATION_ID" VARCHAR2(10 BYTE), 
	"APP_ID" VARCHAR2(4 BYTE)
   )  ;
 

   COMMENT ON COLUMN "UM_LOCATIONID_APP"."LOCATION_ID" IS 'Location Id of Mapping in UM_LOCATION_ID and APPLICATION_ID table';
 
   COMMENT ON COLUMN "UM_LOCATIONID_APP"."APP_ID" IS 'App Id of Mapping in UM_LOCATION_ID and APPLICATION_ID table';

     ALTER TABLE "UM_LOCATIONID_APP" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "UM_LOCATIONID_APP" MODIFY ("APP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "UM_LOCATIONID_APP" ADD CONSTRAINT "UM_LOCATIONID_APP_PK" PRIMARY KEY ("LOCATION_ID", "APP_ID");