
  CREATE TABLE UM_PAYMENT_CODE
   (
   "PAYCD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
	"TMSTMPLSTUPD" TIMESTAMP (6),
	"UIDLSTUPD" VARCHAR2(8 BYTE),
	"PAYDESC" VARCHAR2(40 BYTE) NOT NULL ENABLE,
	"AMTPAY" NUMBER(7,2) NOT NULL ENABLE,
	"LSTAMTPAY" NUMBER(7,2),
	"DTLTEFF" DATE,
	"RCIPTPRTIND" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"DOCISSUIND" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"CATDEF" VARCHAR2(1 BYTE),
	"REVENCD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
	"CHKTRKIND" VARCHAR2(1 BYTE),
	"PAYDESC_CHN" VARCHAR2(80 BYTE)
   );


   COMMENT ON COLUMN "UM_PAYMENT_CODE"."PAYCD" IS 'PAYMENT CODE';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."TMSTMPLSTUPD" IS 'LAST UPDATE TIMESTAMP';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."UIDLSTUPD" IS 'LAST UPDATE USER ID (STANDARD ATTRIBUTE)';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."PAYDESC" IS 'PAYMENT PURPOSE DESCRIPTION';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."AMTPAY" IS 'AMOUNT PAYABLE';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."LSTAMTPAY" IS 'LAST PAYABLE AMOUNT';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."DTLTEFF" IS 'EFFECTIVE DATE';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."RCIPTPRTIND" IS 'RECEIPT PRINT INDICATOR';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."DOCISSUIND" IS 'DOCUMENT ISSUE INDICATOR';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."CATDEF" IS 'DEFAULT CATEGORY';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."REVENCD" IS 'REVENUE CODE';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."CHKTRKIND" IS 'CHECK TRACK INDICATOR';

   COMMENT ON COLUMN "UM_PAYMENT_CODE"."PAYDESC_CHN" IS 'PAYMENT PURPOSE DESCRIPTION (CHINESE)';

   COMMENT ON TABLE "UM_PAYMENT_CODE"  IS 'PAYMENT CODE';

Insert into UM_PAYMENT_CODE (PAYCD,TMSTMPLSTUPD,UIDLSTUPD,PAYDESC,AMTPAY,LSTAMTPAY,DTLTEFF,RCIPTPRTIND,DOCISSUIND,CATDEF,REVENCD,CHKTRKIND,PAYDESC_CHN) values ('001',to_timestamp('27-JAN-14 18.55.01.128000000','DD-MON-RR HH24.MI.SSXFF'),null,'RE-TEST BY ISAE TEAM!!',999,0,to_date('03-JAN-08','DD-MON-RR'),'Y','N',null,'028','N','??');
Insert into UM_PAYMENT_CODE (PAYCD,TMSTMPLSTUPD,UIDLSTUPD,PAYDESC,AMTPAY,LSTAMTPAY,DTLTEFF,RCIPTPRTIND,DOCISSUIND,CATDEF,REVENCD,CHKTRKIND,PAYDESC_CHN) values ('002',to_timestamp('27-JAN-14 18.55.01.128000000','DD-MON-RR HH24.MI.SSXFF'),null,'RE-TEST BY ISAE TEAM!!',999,0,to_date('03-JAN-08','DD-MON-RR'),'Y','N',null,'028','N','??');
