  CREATE OR REPLACE VIEW "V_UM_PRICE_PAYMENT"
  (
  "ROW_ID",
  "ENG_APP_NAME", "CHT_APP_NAME", "CHS_APP_NAME"
  ,"ENG_PRICE_NAME", "CHT_PRICE_NAME", "CHS_PRICE_NAME"
  ,"VALID_FROM", "VALID_TO"
  ,"PAYMENT_CODE", "PAYMENT_DESC"
  ,"EFFECTIVE_DATE"
  ,"RECEIPT_PRINT_IND"
  ,"DOC_ISSUE_IND"
  ,"REVENUE_CODE"
  )  AS
  SELECT
  rownum as ROW_ID,
  A.ENG_APP_NAME,A.CHT_APP_NAME,A.CHS_APP_NAME
  ,B.ENG_NAME, B.CHT_NAME, B.CHS_NAME
  ,B.VALID_FROM, B.VALID_TO
  ,C.PAYCD, C.PAYDESC
  ,C.DTLTEFF
  ,C.RCIPTPRTIND
  ,C.DOCISSUIND
  ,C.REVENCD
FROM UM_APPLICATION_CODE A, UM_PRICE_BOOK B, UM_PAYMENT_CODE C
WHERE A.APP_ID	= B.APP_ID AND B.PAYMENT_CODE=C.PAYCD
;
