package com.pccw.immd.adminfunc.domain;
// Generated May 9, 2018 4:40:02 PM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SctlSharePool generated by hbm2java
 */
@Entity
@Table(name="SCTL_SHARE_POOL"
)
public class SctlSharePool  implements java.io.Serializable {


     private BigDecimal poolId;
     private Date lastAllotedDt;
     private Date lastReleaseDt;
     private BigDecimal usageCount;
     private BigDecimal assignedCount;

    public SctlSharePool() {
    }

	
    public SctlSharePool(BigDecimal poolId) {
        this.poolId = poolId;
    }
    public SctlSharePool(BigDecimal poolId, Date lastAllotedDt, Date lastReleaseDt, BigDecimal usageCount, BigDecimal assignedCount) {
       this.poolId = poolId;
       this.lastAllotedDt = lastAllotedDt;
       this.lastReleaseDt = lastReleaseDt;
       this.usageCount = usageCount;
       this.assignedCount = assignedCount;
    }
   
     @Id 

    
    @Column(name="POOL_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPoolId() {
        return this.poolId;
    }
    
    public void setPoolId(BigDecimal poolId) {
        this.poolId = poolId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_ALLOTED_DT")
    public Date getLastAllotedDt() {
        return this.lastAllotedDt;
    }
    
    public void setLastAllotedDt(Date lastAllotedDt) {
        this.lastAllotedDt = lastAllotedDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_RELEASE_DT")
    public Date getLastReleaseDt() {
        return this.lastReleaseDt;
    }
    
    public void setLastReleaseDt(Date lastReleaseDt) {
        this.lastReleaseDt = lastReleaseDt;
    }

    
    @Column(name="USAGE_COUNT", precision=22, scale=0)
    public BigDecimal getUsageCount() {
        return this.usageCount;
    }
    
    public void setUsageCount(BigDecimal usageCount) {
        this.usageCount = usageCount;
    }

    
    @Column(name="ASSIGNED_COUNT", precision=22, scale=0)
    public BigDecimal getAssignedCount() {
        return this.assignedCount;
    }
    
    public void setAssignedCount(BigDecimal assignedCount) {
        this.assignedCount = assignedCount;
    }




}


