package com.pccw.immd.adminfunc.domain;
// Generated May 9, 2018 4:40:02 PM by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SctlSvcTicketId generated by hbm2java
 */
@Embeddable
public class SctlSvcTicketId  implements java.io.Serializable {


     private String ticketId;
     private String svcId;

    public SctlSvcTicketId() {
    }

    public SctlSvcTicketId(String ticketId, String svcId) {
       this.ticketId = ticketId;
       this.svcId = svcId;
    }
   


    @Column(name="TICKET_ID", nullable=false, length=20)
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }


    @Column(name="SVC_ID", nullable=false, length=3)
    public String getSvcId() {
        return this.svcId;
    }
    
    public void setSvcId(String svcId) {
        this.svcId = svcId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SctlSvcTicketId) ) return false;
		 SctlSvcTicketId castOther = ( SctlSvcTicketId ) other; 
         
		 return ( (this.getTicketId()==castOther.getTicketId()) || ( this.getTicketId()!=null && castOther.getTicketId()!=null && this.getTicketId().equals(castOther.getTicketId()) ) )
 && ( (this.getSvcId()==castOther.getSvcId()) || ( this.getSvcId()!=null && castOther.getSvcId()!=null && this.getSvcId().equals(castOther.getSvcId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTicketId() == null ? 0 : this.getTicketId().hashCode() );
         result = 37 * result + ( getSvcId() == null ? 0 : this.getSvcId().hashCode() );
         return result;
   }   


}


