package com.pccw.immd.adminfunc.domain;
// Generated May 9, 2018 4:40:02 PM by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SctlTrendId generated by hbm2java
 */
@Embeddable
public class SctlTrendId  implements java.io.Serializable {


     private String svcId;
     private Date lastUpdateDt;

    public SctlTrendId() {
    }

    public SctlTrendId(String svcId, Date lastUpdateDt) {
       this.svcId = svcId;
       this.lastUpdateDt = lastUpdateDt;
    }
   


    @Column(name="SVC_ID", nullable=false, length=50)
    public String getSvcId() {
        return this.svcId;
    }
    
    public void setSvcId(String svcId) {
        this.svcId = svcId;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATE_DT", nullable=false)
    public Date getLastUpdateDt() {
        return this.lastUpdateDt;
    }
    
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SctlTrendId) ) return false;
		 SctlTrendId castOther = ( SctlTrendId ) other; 
         
		 return ( (this.getSvcId()==castOther.getSvcId()) || ( this.getSvcId()!=null && castOther.getSvcId()!=null && this.getSvcId().equals(castOther.getSvcId()) ) )
 && ( (this.getLastUpdateDt()==castOther.getLastUpdateDt()) || ( this.getLastUpdateDt()!=null && castOther.getLastUpdateDt()!=null && this.getLastUpdateDt().equals(castOther.getLastUpdateDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSvcId() == null ? 0 : this.getSvcId().hashCode() );
         result = 37 * result + ( getLastUpdateDt() == null ? 0 : this.getLastUpdateDt().hashCode() );
         return result;
   }   


}


