package com.pccw.immd.adminfunc.domain;
// Generated May 9, 2018 4:40:02 PM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SctlAuditId generated by hbm2java
 */
@Embeddable
public class SctlAuditId  implements java.io.Serializable {


     private BigDecimal auditId;
     private Date releaseDt;

    public SctlAuditId() {
    }

    public SctlAuditId(BigDecimal auditId, Date releaseDt) {
       this.auditId = auditId;
       this.releaseDt = releaseDt;
    }
   


    @Column(name="AUDIT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getAuditId() {
        return this.auditId;
    }
    
    public void setAuditId(BigDecimal auditId) {
        this.auditId = auditId;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RELEASE_DT", nullable=false)
    public Date getReleaseDt() {
        return this.releaseDt;
    }
    
    public void setReleaseDt(Date releaseDt) {
        this.releaseDt = releaseDt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SctlAuditId) ) return false;
		 SctlAuditId castOther = ( SctlAuditId ) other; 
         
		 return ( (this.getAuditId()==castOther.getAuditId()) || ( this.getAuditId()!=null && castOther.getAuditId()!=null && this.getAuditId().equals(castOther.getAuditId()) ) )
 && ( (this.getReleaseDt()==castOther.getReleaseDt()) || ( this.getReleaseDt()!=null && castOther.getReleaseDt()!=null && this.getReleaseDt().equals(castOther.getReleaseDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAuditId() == null ? 0 : this.getAuditId().hashCode() );
         result = 37 * result + ( getReleaseDt() == null ? 0 : this.getReleaseDt().hashCode() );
         return result;
   }   


}


