-- MENU
select *
from UM_ROLE_GROUP UM
INNER JOIN UM_GROUP G ON UM.GROUP_ID = G.GROUP_ID
INNER JOIN UM_GROUP_FUNC GF ON UM.GROUP_ID = GF.GROUP_ID
INNER JOIN UM_FUNC F ON GF.FUNC_ID = F.FUNC_ID
WHERE F.ENABLE = 'Y' AND
UM.ROLE_CD IN ('IO(A)OS');

select * from
um_func f
inner join um_group_func gf on f.func_id = gf.func_id
where length(F.FUNC_ID) = 4;


select UM.ROLE_CD, UM.GROUP_ID, UM.ROLE_ID
--, F.FUNC_ID
from UM_ROLE_GROUP UM
INNER JOIN UM_GROUP G ON UM.GROUP_ID = G.GROUP_ID
INNER JOIN UM_GROUP_FUNC GF ON UM.GROUP_ID = GF.GROUP_ID
INNER JOIN UM_FUNC F ON GF.FUNC_ID = F.FUNC_ID and F.ENABLE = 'Y'
WHERE
UM.ROLE_CD IN ('IO(A)OS','IO(A)IS2','IO(A)SD1','IO(A)FS1','IO(SS)AE7','SIO(BD)S1','SIO(BD)S2','IO(BD)S1','IO(BD)S2','SIO(HC)O1','SIO(HC)O2','IO(HC)OS')
;

SELECT * FROM UM_GROUP_FUNC
WHERE FUNC_ID IN ('ADM0007');



select UM.ROLE_CD, UM.GROUP_ID, UM.ROLE_ID, F.FUNC_ID
from UM_ROLE_GROUP UM
INNER JOIN UM_GROUP G ON UM.GROUP_ID = G.GROUP_ID
INNER JOIN UM_GROUP_FUNC GF ON UM.GROUP_ID = GF.GROUP_ID
INNER JOIN UM_FUNC F ON GF.FUNC_ID = F.FUNC_ID
WHERE F.ENABLE = 'Y' AND length(F.FUNC_ID) = 4
AND
UM.ROLE_CD IN ('IO(A)OS','IO(A)IS2','IO(A)SD1','IO(A)FS1','IO(SS)AE7','SIO(BD)S1','SIO(BD)S2','IO(BD)S1','IO(BD)S2','SIO(HC)O1','SIO(HC)O2','IO(HC)OS')
;

SELECT * FROM UM_ROLE_GROUP;

INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)OS', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)IS2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)SD1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)FS1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(SS)AE7', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(BD)S1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(BD)S2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(BD)S1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(BD)S2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(HC)O1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(HC)O2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(HC)OS', 'UAT_TEST', '0003');

SELECT * FROM UM_GROUP;

INSERT INTO UM_GROUP (GROUP_ID, GROUP_DESC, DISPLAY_POS, LST_UPD_ID, LST_UPD_DT)
VALUES ('UAT_TEST', 'UAT Testing Group', null, 'ADMIN', sysdate);

INSERT INTO UM_GROUP_FUNC (GROUP_ID, FUNC_ID)
SELECT 'UAT_TEST', FUNC_ID FROM UM_FUNC
WHERE length(FUNC_ID) = 4;


-- OFFICE
select *
from UPMS_MAPPING UM
INNER JOIN UM_ROLE_OFFICE RO ON UM.OFFICE_CODE = RO.OFFICE_CODE
INNER JOIN UM_OFFICE O ON O.OFFICE_CODE = UM.OFFICE_CODE
;




// UAT UDPATED 201804161121
select *
from UM_ROLE_GROUP UM
INNER JOIN UM_GROUP G ON UM.GROUP_ID = G.GROUP_ID
INNER JOIN UM_GROUP_FUNC GF ON UM.GROUP_ID = GF.GROUP_ID
INNER JOIN UM_FUNC F ON GF.FUNC_ID = F.FUNC_ID
WHERE F.ENABLE = 'Y' AND
UM.ROLE_CD IN ('IO(A)OS');


INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)OS', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)IS2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)SD1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(A)FS1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(SS)AE7', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(BD)S1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(BD)S2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(BD)S1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(BD)S2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(HC)O1', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('SIO(HC)O2', 'UAT_TEST', '0003');
INSERT INTO UM_ROLE_GROUP (ROLE_CD, GROUP_ID, ROLE_ID) VALUES ('IO(HC)OS', 'UAT_TEST', '0003');


INSERT INTO UM_GROUP (GROUP_ID, GROUP_DESC, DISPLAY_POS, LST_UPD_ID, LST_UPD_DT)
VALUES ('UAT_TEST', 'UAT Testing Group', null, 'ADMIN', sysdate);

SELECT * FROM UM_FUNC
WHERE length(FUNC_ID) = 4;

UPDATE UM_FUNC SET DISPLAY_POS = 9 WHERE FUNC_ID = 'EC01';
UPDATE UM_FUNC SET DISPLAY_POS = 4 WHERE FUNC_ID = 'EC10';
UPDATE UM_FUNC SET DISPLAY_POS = 3 WHERE FUNC_ID = 'EC02';
UPDATE UM_FUNC SET DISPLAY_POS = 13 WHERE FUNC_ID = 'EC07';

INSERT INTO UM_GROUP_FUNC (GROUP_ID, FUNC_ID)
SELECT 'UAT_TEST', FUNC_ID FROM UM_FUNC
WHERE length(FUNC_ID) = 4;

