CREATE TABLE "UM_GROUP"
   (	"GROUP_ID" VARCHAR2(16 BYTE),
	"GROUP_DESC" VARCHAR2(256 BYTE),
	"DISPLAY_POS" VARCHAR2(3 BYTE),
	"LST_UPD_ID" VARCHAR2(10 BYTE),
	"LST_UPD_DT" DATE
   );

  ALTER TABLE "UM_GROUP" ADD CONSTRAINT "UM_GROUP_PK" PRIMARY KEY ("GROUP_ID");



INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('INVUser','INV User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('Imp_Announcement','Importnat Announcement');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('MNQuotaTransfer','Transfer of M-quota to K-quota');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ES Booking Sup','Supervisor of ES Booking Service');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ES Booking User','User of ES Booking Service');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('TD AccessControl','Access Control of TD Booking Service');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('RMSup','RM Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('BirthRegSup','Supervisor of Birth Registration');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('BDMSup','BDM Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('BDMUser','BDM User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('UserAdm','User Administration');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ROASup','ROA Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ROAUser','ROA User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('RMUser','RM User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('INVSup','INV Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('PMTSup','PMT Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('PMTUser','PMT User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('TDSup','TD Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ALL','ALL function');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('Enq_Code','Enquiry Code Information');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('MNUser','Marriage Registries User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('MNSup','Marriage Registries Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ROPIBOSup','ROP/IBO Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ROPIBOUser','ROP/IBO User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ESAppln User','User of ES Application Service');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('ESAppln Sup','Supervisor of ES Application Service');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('TD Coll Sup','TD Collection Booking Supervisor');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('Email Address','Email address for receiving notification');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('QuotaRelease','Quota Release Rule');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('BirthRegUser','User of Birth Registration');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('TD Coll User','TD Collection Booking User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('Del_Appointment','Delete Appointment Booking');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('TDUser','TD User');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('QuotaMaint','Quota Maintenance');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('VirtualAppEnq','Virtual Appointment Enquiry ');
INSERT INTO UM_GROUP (GROUP_ID,GROUP_DESC) VALUES ('VirtualSizeMaint','Virtual Quota Multiplier Maintenance');
