--------------------------------------------------------
--  DDL for Table UM_LOCATIONID
--------------------------------------------------------

CREATE TABLE "UM_LOCATIONID"
   (	"LOCATION_ID" VARCHAR2(10 BYTE),
	"LOCATION_NAME" VARCHAR2(50 BYTE),
    "ENG_APP_NAME" VARCHAR2(250 BYTE),
	"FM_EFFECTIVE_DATE" TIMESTAMP (6),
	"TO_EFFECTIVE_DATE" TIMESTAMP (6),
	"STATUS" VARCHAR2(1 BYTE),
	"CREATE_AT" TIMESTAMP (6),
	"MODIFIED_AT" TIMESTAMP (6)
   )  ;


  COMMENT ON COLUMN "UM_LOCATIONID"."LOCATION_ID" IS 'Primary key for this table';

  COMMENT ON COLUMN "UM_LOCATIONID"."LOCATION_NAME" IS 'Full Location ID Name';

  COMMENT ON COLUMN "UM_LOCATIONID"."FM_EFFECTIVE_DATE" IS 'Effective start date and time';

  COMMENT ON COLUMN "UM_LOCATIONID"."TO_EFFECTIVE_DATE" IS 'Effective end date and time';

  COMMENT ON COLUMN "UM_LOCATIONID"."STATUS" IS 'Y ? Enable, N ? Disable';

  COMMENT ON COLUMN "UM_LOCATIONID"."CREATE_AT" IS 'Create date time of this record';

  COMMENT ON COLUMN "UM_LOCATIONID"."MODIFIED_AT" IS 'Last modified date time of this record';

  ALTER TABLE "UM_LOCATIONID" MODIFY ("LOCATION_ID" NOT NULL ENABLE);

  ALTER TABLE "UM_LOCATIONID" MODIFY ("LOCATION_NAME" NOT NULL ENABLE);

  ALTER TABLE "UM_LOCATIONID" MODIFY ("STATUS" NOT NULL ENABLE);

  ALTER TABLE "UM_LOCATIONID" ADD CONSTRAINT "UM_LOCATIONID_PK" PRIMARY KEY ("LOCATION_ID")



INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','BDM','Birth, Death, Marriage');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','COE','COE');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','Controller','Location Controller');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','IBO/ROP','IBO/ROP');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','INV','INV');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','RM','RM');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','ROA','ROA');
INSERT INTO UM_LOCATIONID (STATUS,LOCATION_ID,LOCATION_NAME) VALUES ('Y','TD','Travel Document');


