
  CREATE TABLE "UM_LOCATIONID_APP"
   (	"LOCATION_ID" VARCHAR2(10 BYTE),
	"APP_ID" VARCHAR2(4 BYTE)
   )  ;


   COMMENT ON COLUMN "UM_LOCATIONID_APP"."LOCATION_ID" IS 'Location Id of Mapping in UM_LOCATION_ID and APPLICATION_ID table';

   COMMENT ON COLUMN "UM_LOCATIONID_APP"."APP_ID" IS 'App Id of Mapping in UM_LOCATION_ID and APPLICATION_ID table';

     ALTER TABLE "UM_LOCATIONID_APP" MODIFY ("LOCATION_ID" NOT NULL ENABLE);

  ALTER TABLE "UM_LOCATIONID_APP" MODIFY ("APP_ID" NOT NULL ENABLE);

  ALTER TABLE "UM_LOCATIONID_APP" ADD CONSTRAINT "UM_LOCATIONID_APP_PK" PRIMARY KEY ("LOCATION_ID", "APP_ID");




INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','502');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','503');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','563');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','564');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','565');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','568');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','569');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','570');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','577');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','619');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('BDM','640');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('COE','634');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','500');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','501');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','502');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','503');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','504');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','505');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','509');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','519');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','520');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','524');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','527');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','563');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','564');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','565');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','568');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','569');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','570');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','576');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','577');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','579');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','584');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','586');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','590');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','591');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','592');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','596');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','597');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','618');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','619');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','622');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','623');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','630');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','634');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','640');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','642');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','643');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('Controller','644');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','500');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','501');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','505');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','509');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','519');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','520');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','579');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','597');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('IBO/ROP','618');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('INV','586');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('PNV','576');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('PNV','592');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('PNV','596');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('PNV','597');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('RM','527');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('RM','584');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('ROA','590');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('ROA','591');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('ROA','592');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','500');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','501');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','505');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','509');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','519');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','520');
INSERT INTO UM_LOCATIONID_APP (LOCATION_ID,APP_ID) VALUES ('TD','618');


