

  CREATE TABLE "UM_ROLE_OFFICE"
   (	"ROLD_ID" VARCHAR2(4 BYTE),
	"OFFICE_CODE" VARCHAR2(10 BYTE)
   );

  ALTER TABLE "UM_ROLE_OFFICE" MODIFY ("ROLD_ID" NOT NULL ENABLE);

  ALTER TABLE "UM_ROLE_OFFICE" MODIFY ("OFFICE_CODE" NOT NULL ENABLE);

  ALTER TABLE "UM_ROLE_OFFICE" ADD CONSTRAINT "UM_ROLE_OFFICE_PK" PRIMARY KEY ("ROLD_ID", "OFFICE_CODE");



INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','BDM(S)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','CHR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','CTDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','GRO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','HKDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','KBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','KDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','MRRO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','STBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','STMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','TMBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','TMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('BDM','TSTR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('COE','COE');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','BDM(S)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','CHR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','COE');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','CTDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','DM');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','EKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','EKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ES');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','EVV');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','FDH3');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','FDH6');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','FTS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','GRO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','HKDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','HKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','IS(AE)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','KBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','KDR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','MRRO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','OI');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','OVP');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','QMMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','RM');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROA');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP(S)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP-FTO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP-HKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP-KO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP-KTO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','ROP-YLO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','SHS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','SS(SA)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','STBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','STMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','STO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TDI');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TDNA');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TDS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TMBR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TPO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','TSTR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','WKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','WKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','YLO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('Controller','YLS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','DM');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','EKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','EKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','FTS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','HKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP(S)');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP-FTO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP-HKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP-KO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP-KTO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','ROP-YLO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','SHS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','STO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','TDS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','TPO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','WKO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','WKS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','YLO');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('IBO/ROP','YLS');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('INV','OI');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','ES');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','EVV');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','FDH3');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','FDH6');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','OVP');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('PNV','QMMR');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('RM','RM');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('ROA','ROA');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('TD','TDI');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('TD','TDNA');
INSERT INTO UM_LOCATIONID_OFFICE (LOCATION_ID,OFFICE_CODE) VALUES ('TD','TDS');
