CREATE TABLE "UM_OFFICE"
   (
    "OFFICE_CODE" VARCHAR2(10 BYTE),
    "DISPLAY_CODE" VARCHAR2(10 BYTE),
    "DISPLAY_NAME" VARCHAR2(100 BYTE),
    "DISPLAY_OFFICE_CODE" VARCHAR2(10 BYTE),
    "DISPLAY_ENG_OFFICE_NAME" VARCHAR2(100 BYTE),
    primary key(OFFICE_CODE)
   ) ;


INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('BDM(S)','BDM(S)','Births, Deaths and Marriage (Support) Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('CHR','CHR','City Hall Marriage Registry','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('CTDR','CTDR','Cotton Tree Drive Marriage Registry ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('GRO','GRO','The Births and Deaths General Register Office','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('HKDR','HKDR','The Births and Deaths General Register Office (Hong Kong Island Deaths Registry)','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('KBR','KBR','Kowloon Births Registry','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('KDR','KDR','The Births and Deaths General Register Office (Kowloon Deaths Registry) ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('MRRO','MRRO','Marriage Registration and Records Office ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('STBR','STBR','Sha Tin District Births Registry ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('STMR','STMR','Sha Tin Marriage Registry ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TMBR','TMBR','Tuen Mun District Births Registry ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TMR','TMMR','Tuen Mun Marriage Registry','TMMR','Tuen Mun Marriage Registry');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TSTR','TSTR','Tsim Sha Tsui Marriage Registry','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('COE','COE','Certificate of Entitlement Section','COE','Certificate of Entitlement Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('DM','DM','Document Management Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('EKO','EKO','Immigration - East Kowloon Office','EKO','Immigration - East Kowloon Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('EKS','EKO','Immigration - East Kowloon Office','EKO','Immigration - East Kowloon Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ES','ES','Extension Section','ES','Extension Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('EVV','EVV','Employment and Visit Visas Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('FDH3','FDH','Foreign Domestic Helpers Section','FDH','Foreign Domestic Helpers Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('FDH6','FDH','Foreign Domestic Helpers Section','FDH','Foreign Domestic Helpers Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('FTS','FTO','Immigration - Fo Tan Office','FTO','Immigration - Fo Tan Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('HKS','HKO','Immigration - Hong Kong Island Travel Documents Issuing Office','HKO','Immigration - Hong Kong Island Travel Documents Issuing Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('OI','OI','Outside Investigation Section ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('OVP','OVP','Other Visas and Permits Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('QMMR','QMMR','Quality Migrants and Mainland Residents Section','QMMR','Quality Migrants and Mainland Residents Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('RM','RM','Record and Data Management Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROA','ROA','Right of Abode Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP(S)','ROP(S)','Registration of Persons (Support) Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP-FTO','ROP-FTO','Registration of Persons - Fo Tan Office','ROP-FTO','Registration of Persons - Fo Tan Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP-HKO','ROP-HKO','Registration of Persons - Hong Kong Office','ROP-HKO','Registration of Persons - Hong Kong Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP-KO','ROP-KO','Registration of Persons - Kowloon Office','ROP-KO','Registration of Persons - Kowloon Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP-KTO','ROP-KTO','Registration of Persons - Kwun Tong Office','ROP-KTO','Registration of Persons - Kwun Tong Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('ROP-YLO','ROP-YLO','Registration of Persons - Yuen Long Office','ROP-YLO','Registration of Persons - Yuen Long Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('SHS','STO','Immigration - Sha Tin Office','STO','Immigration - Sha Tin Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('SS(SA)','SS(SA)','Systems Support (Security and Administrative Network) Section ','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('STO','STO','Immigration - Sha Tin Office','STO','Immigration - Sha Tin Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TDI','TDI','Travel Documents (Issue) Section','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TDNA','TDNA','"Travel Documents and Nationality (Application) Section, Immigration Headquarters
(Wan Chai)"','','');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TDS','TDI','Travel Documents (Issue) Section','TDI','Travel Documents (Issue) Section');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('TPO','FTO','Immigration - Fo Tan Office','FTO','Immigration - Fo Tan Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('WKO','WKO','Immigration - West Kowloon Office','WKO','Immigration - West Kowloon Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('WKS','WKO','Immigration - West Kowloon Office','WKO','Immigration - West Kowloon Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('YLO','YLO','Immigration - Yuen Long Office','YLO','Immigration - Yuen Long Office');
INSERT INTO UM_OFFICE (OFFICE_CODE,DISPLAY_CODE,DISPLAY_NAME,DISPLAY_OFFICE_CODE,DISPLAY_ENG_OFFICE_NAME) VALUES ('YLS','YLO','Immigration - Yuen Long Office','YLO','Immigration - Yuen Long Office');
