  CREATE TABLE "UM_ROLE"
   (	"ROLE_ID" VARCHAR2(4 BYTE),
	"ROLE_DESC" VARCHAR2(128 BYTE),
	"DELEGATE_PRI" VARCHAR2(1 BYTE),
	"DISPLAY_POS" VARCHAR2(2 BYTE)
   );


Insert into UM_ROLE (ROLE_ID,ROLE_DESC,DELEGATE_PRI,DISPLAY_POS) values ('0001','Controller','Y','1');
Insert into UM_ROLE (ROLE_ID,ROLE_DESC,DELEGATE_PRI,DISPLAY_POS) values ('0002','Supervisor','Y','2');
Insert into UM_ROLE (ROLE_ID,ROLE_DESC,DELEGATE_PRI,DISPLAY_POS) values ('0003','User','Y','3');