/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.pccw.immd.adminfunc.web.rest;

import javax.validation.Valid;

import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.pccw.immd.adminfunc.dto.UpmsUser;
import com.pccw.immd.adminfunc.dto.UserDTO;
import com.pccw.immd.adminfunc.dto.ValidationerrorDTO;
import ws.upms.immd.v1.ITIAppException;
import ws.upms.immd.v1.ITISysException;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-01T03:56:21.323Z")

@Api(value = "${server.contextPath}/auth")
public interface AuthApi {

    @ApiOperation(
    		value = "UMPS Integration for user authentication", 
    		notes = "No need to provide the terminial ID.", 
    		response = String.class, 
    		tags={ "adminfunc"}
    )
    @ApiResponses(value = {
//        @ApiResponse(code = 201, message = "Return success message", response = String.class),
//        @ApiResponse(code = 400, message = "Return validation error", response = ValidationerrorDTO.class),
//    	@ApiResponse(code = 401, message = "Return auth error", response = ValidationerrorDTO.class)
    })

    @RequestMapping(value = "/login/",
//        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.POST)
    UpmsUser login(@ApiParam(value = "", required = true) @RequestBody  @Valid  UserDTO userDTO)  throws ITIAppException, ITISysException;

}
