
package ws.cds.immd.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-04-05T20:08:41.743+08:00
 * Generated source version: 3.1.14
 */

@WebFault(name = "CoreAppException", targetNamespace = "http://immd.itifwk.util/v1")
public class CoreAppExceptionException extends Exception {
    
    private util.itifwk.immd.v1.CoreAppException coreAppException;

    public CoreAppExceptionException() {
        super();
    }
    
    public CoreAppExceptionException(String message) {
        super(message);
    }
    
    public CoreAppExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public CoreAppExceptionException(String message, util.itifwk.immd.v1.CoreAppException coreAppException) {
        super(message);
        this.coreAppException = coreAppException;
    }

    public CoreAppExceptionException(String message, util.itifwk.immd.v1.CoreAppException coreAppException, Throwable cause) {
        super(message, cause);
        this.coreAppException = coreAppException;
    }

    public util.itifwk.immd.v1.CoreAppException getFaultInfo() {
        return this.coreAppException;
    }
}
