
package ws.cds.immd.v1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-22T15:10:28.163+08:00
 * Generated source version: 3.2.3
 *
 */


public class EnquireTransactionGroupServiceWS_EnquireTransactionGroupServiceWSImplPort_Server {

    protected EnquireTransactionGroupServiceWS_EnquireTransactionGroupServiceWSImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new EnquireTransactionGroupServiceWSImplPortImpl();
//        String address = "http://172.16.223.6:29080/icons/upms/enquireTranGpSvc";
        String address = "http://localhost:8080/admin-func/services/EnquireTransactionGroupServiceWSImplPortImpl";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new EnquireTransactionGroupServiceWS_EnquireTransactionGroupServiceWSImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
