package ws.cds.immd.v1;

import io.swagger.annotations.Api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.core.MediaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-22T15:10:28.156+08:00
 * Generated source version: 3.2.3
 *
 */
@Api(value = "Administrative Function POST -> FuncId(TxId)",
        consumes = MediaType.APPLICATION_XML,
        produces = MediaType.APPLICATION_XML)


@WebService(targetNamespace = "http://immd.cds.ws/v1", name = "EnquireTransactionGroupServiceWS")
@XmlSeeAlso({ObjectFactory.class, util.itifwk.immd.v1.ObjectFactory.class})
public interface EnquireTransactionGroupServiceWS {

    @WebMethod
    @RequestWrapper(localName = "enquireAllData", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireAllData")
    @ResponseWrapper(localName = "enquireAllDataResponse", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireAllDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ws.cds.immd.v1.RoleTxgpTxidDTO enquireAllData() throws VLDExceptionException, CoreAppExceptionException;

    @WebMethod
    @RequestWrapper(localName = "enquireTransactionGroup", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireTransactionGroup")
    @ResponseWrapper(localName = "enquireTransactionGroupResponse", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireTransactionGroupResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ws.cds.immd.v1.TransGrpRoleDTO> enquireTransactionGroup(
            @WebParam(name = "roleCdList", targetNamespace = "")
                    java.util.List<java.lang.String> roleCdList
    ) throws VLDExceptionException, CoreAppExceptionException;

    @WebMethod
    @RequestWrapper(localName = "enquireTxIDsByRoleCd", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireTxIDsByRoleCd")
    @ResponseWrapper(localName = "enquireTxIDsByRoleCdResponse", targetNamespace = "http://immd.cds.ws/v1", className = "ws.cds.immd.v1.EnquireTxIDsByRoleCdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ws.cds.immd.v1.Txid> enquireTxIDsByRoleCd(
            @WebParam(name = "roleCd", targetNamespace = "")
                    java.lang.String roleCd
    );
}
