
package ws.cds.immd.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-04-05T20:08:41.693+08:00
 * Generated source version: 3.1.14
 */

@WebFault(name = "VLDException", targetNamespace = "http://immd.itifwk.util/v1")
public class VLDExceptionException extends Exception {
    
    private util.itifwk.immd.v1.VLDException vldException;

    public VLDExceptionException() {
        super();
    }
    
    public VLDExceptionException(String message) {
        super(message);
    }
    
    public VLDExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public VLDExceptionException(String message, util.itifwk.immd.v1.VLDException vldException) {
        super(message);
        this.vldException = vldException;
    }

    public VLDExceptionException(String message, util.itifwk.immd.v1.VLDException vldException, Throwable cause) {
        super(message, cause);
        this.vldException = vldException;
    }

    public util.itifwk.immd.v1.VLDException getFaultInfo() {
        return this.vldException;
    }
}
