package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 28, 2018 12:45:46 PM by Hibernate Tools 5.0.6.Final


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * AppointmentInfo generated by hbm2java
 */
@Entity
@Table(name="APPOINTMENT_INFO"
)
public class AppointmentInfo {


     private AppointmentInfoId id;
     private BigDecimal quotaId;
     private Date apptEndtime;
     private String serviceType;
     private String apmidType;
     private String apmidCode;
     private String appDob;
     private String servicesNature;
     private String ageInd;
     private String prefilInd;
     private String active;
     private Date createDate;
     private String createBy;
     private Date lastUpdDate;
     private String lastUpdBy;

    public AppointmentInfo() {
    }

    public AppointmentInfo(AppointmentInfoId id, BigDecimal quotaId, Date apptEndtime, String serviceType, String apmidType, String apmidCode, String appDob, String servicesNature, String ageInd, String prefilInd, String active, Date createDate, String createBy, Date lastUpdDate, String lastUpdBy) {
       this.id = id;
       this.quotaId = quotaId;
       this.apptEndtime = apptEndtime;
       this.serviceType = serviceType;
       this.apmidType = apmidType;
       this.apmidCode = apmidCode;
       this.appDob = appDob;
       this.servicesNature = servicesNature;
       this.ageInd = ageInd;
       this.prefilInd = prefilInd;
       this.active = active;
       this.createDate = createDate;
       this.createBy = createBy;
       this.lastUpdDate = lastUpdDate;
       this.lastUpdBy = lastUpdBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="trn", column=@Column(name="TRN", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="groupMemId", column=@Column(name="GROUP_MEM_ID", nullable=false, length=3) ) } )
    public AppointmentInfoId getId() {
        return this.id;
    }
    
    public void setId(AppointmentInfoId id) {
        this.id = id;
    }

    
    @Column(name="QUOTA_ID", nullable=false, precision=38, scale=0)
    public BigDecimal getQuotaId() {
        return this.quotaId;
    }
    
    public void setQuotaId(BigDecimal quotaId) {
        this.quotaId = quotaId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPT_ENDTIME", nullable=false)
    public Date getApptEndtime() {
        return this.apptEndtime;
    }
    
    public void setApptEndtime(Date apptEndtime) {
        this.apptEndtime = apptEndtime;
    }

    
    @Column(name="SERVICE_TYPE", nullable=false, length=3)
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    
    @Column(name="APMID_TYPE", nullable=false, length=2)
    public String getApmidType() {
        return this.apmidType;
    }
    
    public void setApmidType(String apmidType) {
        this.apmidType = apmidType;
    }

    
    @Column(name="APMID_CODE", nullable=false, length=8)
    public String getApmidCode() {
        return this.apmidCode;
    }
    
    public void setApmidCode(String apmidCode) {
        this.apmidCode = apmidCode;
    }

    
    @Column(name="APP_DOB", nullable=false, length=8)
    public String getAppDob() {
        return this.appDob;
    }
    
    public void setAppDob(String appDob) {
        this.appDob = appDob;
    }

    
    @Column(name="SERVICES_NATURE", nullable=false, length=1)
    public String getServicesNature() {
        return this.servicesNature;
    }
    
    public void setServicesNature(String servicesNature) {
        this.servicesNature = servicesNature;
    }

    
    @Column(name="AGE_IND", nullable=false, length=1)
    public String getAgeInd() {
        return this.ageInd;
    }
    
    public void setAgeInd(String ageInd) {
        this.ageInd = ageInd;
    }

    
    @Column(name="PREFIL_IND", nullable=false, length=1)
    public String getPrefilInd() {
        return this.prefilInd;
    }
    
    public void setPrefilInd(String prefilInd) {
        this.prefilInd = prefilInd;
    }

    
    @Column(name="ACTIVE", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_BY", nullable=false, length=3)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPD_DATE", nullable=false)
    public Date getLastUpdDate() {
        return this.lastUpdDate;
    }
    
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    
    @Column(name="LAST_UPD_BY", nullable=false, length=3)
    public String getLastUpdBy() {
        return this.lastUpdBy;
    }
    
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }




}


