package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 28, 2018 12:45:46 PM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppointmentInfoId generated by hbm2java
 */
@Embeddable
public class AppointmentInfoId  implements java.io.Serializable {


     private BigDecimal trn;
     private String groupMemId;

    public AppointmentInfoId() {
    }

    public AppointmentInfoId(BigDecimal trn, String groupMemId) {
       this.trn = trn;
       this.groupMemId = groupMemId;
    }
   


    @Column(name="TRN", nullable=false, precision=38, scale=0)
    public BigDecimal getTrn() {
        return this.trn;
    }
    
    public void setTrn(BigDecimal trn) {
        this.trn = trn;
    }


    @Column(name="GROUP_MEM_ID", nullable=false, length=3)
    public String getGroupMemId() {
        return this.groupMemId;
    }
    
    public void setGroupMemId(String groupMemId) {
        this.groupMemId = groupMemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppointmentInfoId) ) return false;
		 AppointmentInfoId castOther = ( AppointmentInfoId ) other; 
         
		 return ( (this.getTrn()==castOther.getTrn()) || ( this.getTrn()!=null && castOther.getTrn()!=null && this.getTrn().equals(castOther.getTrn()) ) )
 && ( (this.getGroupMemId()==castOther.getGroupMemId()) || ( this.getGroupMemId()!=null && castOther.getGroupMemId()!=null && this.getGroupMemId().equals(castOther.getGroupMemId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTrn() == null ? 0 : this.getTrn().hashCode() );
         result = 37 * result + ( getGroupMemId() == null ? 0 : this.getGroupMemId().hashCode() );
         return result;
   }   


}


