package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 26, 2018 10:17:46 AM by Hibernate Tools 5.0.6.Final


import javax.persistence.*;
import java.util.Date;

/**
 * AppointmentTrans generated by hbm2java
 */
@Entity
@Table(name="APPOINTMENT_TRANS"
)
public class AppointmentTrans {


     private long ern;
     private long trn;
     private Long preErn;
     private Long preTrn;
     private short appId;
     private String exportStatus;
     private String interfaceFile;
     private String controlFile;
     private Date exportTime;
     private short enqCode;
     private Date transTime;
     private String commLang;
     private String commChannel;
     private String commParameter;
     private String faxInd;
     private String isNotSent;
     private String isRemSent;
     private String virtualInd;
     private String action;
     private String active;
     private Date createDate;
     private String createBy;
     private Date lastUpdDate;
     private String lastUpdBy;

    public AppointmentTrans() {
    }

	
    public AppointmentTrans(long ern, long trn, short appId, short enqCode, Date transTime, String commLang, String commChannel, String isNotSent, String isRemSent, String virtualInd, String action, String active, Date createDate, String createBy, Date lastUpdDate, String lastUpdBy) {
        this.ern = ern;
        this.trn = trn;
        this.appId = appId;
        this.enqCode = enqCode;
        this.transTime = transTime;
        this.commLang = commLang;
        this.commChannel = commChannel;
        this.isNotSent = isNotSent;
        this.isRemSent = isRemSent;
        this.virtualInd = virtualInd;
        this.action = action;
        this.active = active;
        this.createDate = createDate;
        this.createBy = createBy;
        this.lastUpdDate = lastUpdDate;
        this.lastUpdBy = lastUpdBy;
    }
    public AppointmentTrans(long ern, long trn, Long preErn, Long preTrn, short appId, String exportStatus, String interfaceFile, String controlFile, Date exportTime, short enqCode, Date transTime, String commLang, String commChannel, String commParameter, String faxInd, String isNotSent, String isRemSent, String virtualInd, String action, String active, Date createDate, String createBy, Date lastUpdDate, String lastUpdBy) {
       this.ern = ern;
       this.trn = trn;
       this.preErn = preErn;
       this.preTrn = preTrn;
       this.appId = appId;
       this.exportStatus = exportStatus;
       this.interfaceFile = interfaceFile;
       this.controlFile = controlFile;
       this.exportTime = exportTime;
       this.enqCode = enqCode;
       this.transTime = transTime;
       this.commLang = commLang;
       this.commChannel = commChannel;
       this.commParameter = commParameter;
       this.faxInd = faxInd;
       this.isNotSent = isNotSent;
       this.isRemSent = isRemSent;
       this.virtualInd = virtualInd;
       this.action = action;
       this.active = active;
       this.createDate = createDate;
       this.createBy = createBy;
       this.lastUpdDate = lastUpdDate;
       this.lastUpdBy = lastUpdBy;
    }
   
     @Id 

    
    @Column(name="ERN", unique=true, nullable=false, precision=16, scale=0)
    public long getErn() {
        return this.ern;
    }
    
    public void setErn(long ern) {
        this.ern = ern;
    }

    
    @Column(name="TRN", nullable=false, precision=16, scale=0)
    public long getTrn() {
        return this.trn;
    }
    
    public void setTrn(long trn) {
        this.trn = trn;
    }

    
    @Column(name="PRE_ERN", precision=16, scale=0)
    public Long getPreErn() {
        return this.preErn;
    }
    
    public void setPreErn(Long preErn) {
        this.preErn = preErn;
    }

    
    @Column(name="PRE_TRN", precision=16, scale=0)
    public Long getPreTrn() {
        return this.preTrn;
    }
    
    public void setPreTrn(Long preTrn) {
        this.preTrn = preTrn;
    }

    
    @Column(name="APP_ID", nullable=false, precision=3, scale=0)
    public short getAppId() {
        return this.appId;
    }
    
    public void setAppId(short appId) {
        this.appId = appId;
    }

    
    @Column(name="EXPORT_STATUS", length=1)
    public String getExportStatus() {
        return this.exportStatus;
    }
    
    public void setExportStatus(String exportStatus) {
        this.exportStatus = exportStatus;
    }

    
    @Column(name="INTERFACE_FILE", length=40)
    public String getInterfaceFile() {
        return this.interfaceFile;
    }
    
    public void setInterfaceFile(String interfaceFile) {
        this.interfaceFile = interfaceFile;
    }

    
    @Column(name="CONTROL_FILE", length=40)
    public String getControlFile() {
        return this.controlFile;
    }
    
    public void setControlFile(String controlFile) {
        this.controlFile = controlFile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPORT_TIME")
    public Date getExportTime() {
        return this.exportTime;
    }
    
    public void setExportTime(Date exportTime) {
        this.exportTime = exportTime;
    }

    
    @Column(name="ENQ_CODE", nullable=false, precision=4, scale=0)
    public short getEnqCode() {
        return this.enqCode;
    }
    
    public void setEnqCode(short enqCode) {
        this.enqCode = enqCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TRANS_TIME", nullable=false)
    public Date getTransTime() {
        return this.transTime;
    }
    
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    
    @Column(name="COMM_LANG", nullable=false, length=6)
    public String getCommLang() {
        return this.commLang;
    }
    
    public void setCommLang(String commLang) {
        this.commLang = commLang;
    }

    
    @Column(name="COMM_CHANNEL", nullable=false, length=1)
    public String getCommChannel() {
        return this.commChannel;
    }
    
    public void setCommChannel(String commChannel) {
        this.commChannel = commChannel;
    }

    
    @Column(name="COMM_PARAMETER", length=200)
    public String getCommParameter() {
        return this.commParameter;
    }
    
    public void setCommParameter(String commParameter) {
        this.commParameter = commParameter;
    }

    
    @Column(name="FAX_IND", length=1)
    public String getFaxInd() {
        return this.faxInd;
    }
    
    public void setFaxInd(String faxInd) {
        this.faxInd = faxInd;
    }

    
    @Column(name="IS_NOT_SENT", nullable=false, length=1)
    public String getIsNotSent() {
        return this.isNotSent;
    }
    
    public void setIsNotSent(String isNotSent) {
        this.isNotSent = isNotSent;
    }

    
    @Column(name="IS_REM_SENT", nullable=false, length=1)
    public String getIsRemSent() {
        return this.isRemSent;
    }
    
    public void setIsRemSent(String isRemSent) {
        this.isRemSent = isRemSent;
    }

    
    @Column(name="VIRTUAL_IND", nullable=false, length=1)
    public String getVirtualInd() {
        return this.virtualInd;
    }
    
    public void setVirtualInd(String virtualInd) {
        this.virtualInd = virtualInd;
    }

    
    @Column(name="ACTION", nullable=false, length=3)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="ACTIVE", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_BY", nullable=false, length=3)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPD_DATE", nullable=false)
    public Date getLastUpdDate() {
        return this.lastUpdDate;
    }
    
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    
    @Column(name="LAST_UPD_BY", nullable=false, length=3)
    public String getLastUpdBy() {
        return this.lastUpdBy;
    }
    
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }




}


