package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 26, 2018 1:27:42 PM by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Holiday generated by hbm2java
 */
@Entity
@Table(name="HOLIDAY"
)
public class Holiday  implements java.io.Serializable {


     private Date publicHoliday;

    public Holiday() {
    }

    public Holiday(Date publicHoliday) {
       this.publicHoliday = publicHoliday;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="PUBLIC_HOLIDAY", length=7)
    public Date getPublicHoliday() {
        return this.publicHoliday;
    }
    
    public void setPublicHoliday(Date publicHoliday) {
        this.publicHoliday = publicHoliday;
    }




}


