package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 24, 2018 4:33:01 PM by Hibernate Tools 5.0.6.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Office generated by hbm2java
 */
@Entity
@Table(name="OFFICE"
)
public class Office  implements Serializable {


     private String officeId;
     private String engRegion;
     private String chtRegion;
     private String chsRegion;
     private String engDistrict;
     private String chtDistrict;
     private String chsDistrict;
     private String engAddr;
     private String chtAddr;
     private String chsAddr;
     private String engAddrHint;
     private String chtAddrHint;
     private String chsAddrHint;
     private String engOffName;
     private String chtOffName;
     private String chsOffName;
     private String telNum;
     private String faxNum;
     private String image;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String engAddrUrl;
     private String chtAddrUrl;
     private String chsAddrUrl;
     private String offHrWdStart1;
     private String offHrWdEnd1;
     private String offHrWdStart2;
     private String offHrWdEnd2;
     private String offHrSatStart1;
     private String offHrSatEnd1;
     private String offHrSatStart2;
     private String offHrSatEnd2;
     private String offHrSunStart1;
     private String offHrSunEnd1;
     private String offHrSunStart2;
     private String offHrSunEnd2;
     private String engOffHrWdNote;
     private String engOffHrSatNote;
     private String engOffHrSunNote;
     private String chtOffHrWdNote;
     private String chtOffHrSatNote;
     private String chtOffHrSunNote;
     private String chsOffHrWdNote;
     private String chsOffHrSatNote;
     private String chsOffHrSunNote;
     private Date effectiveDate;
     private Date createAt;
     private Date modifyAt;
     private String modifyBy;

    public Office() {
    }

	
    public Office(String officeId, String engRegion, String chtRegion, String chsRegion, String engDistrict, String chtDistrict, String chsDistrict, String engAddr, String chtAddr, String chsAddr, String engOffName, String chtOffName, String chsOffName, String telNum, String image, BigDecimal latitude, BigDecimal longitude, String engAddrUrl, String chtAddrUrl, String chsAddrUrl, String offHrWdStart1, Date effectiveDate, Date createAt, Date modifyAt, String modifyBy) {
        this.officeId = officeId;
        this.engRegion = engRegion;
        this.chtRegion = chtRegion;
        this.chsRegion = chsRegion;
        this.engDistrict = engDistrict;
        this.chtDistrict = chtDistrict;
        this.chsDistrict = chsDistrict;
        this.engAddr = engAddr;
        this.chtAddr = chtAddr;
        this.chsAddr = chsAddr;
        this.engOffName = engOffName;
        this.chtOffName = chtOffName;
        this.chsOffName = chsOffName;
        this.telNum = telNum;
        this.image = image;
        this.latitude = latitude;
        this.longitude = longitude;
        this.engAddrUrl = engAddrUrl;
        this.chtAddrUrl = chtAddrUrl;
        this.chsAddrUrl = chsAddrUrl;
        this.offHrWdStart1 = offHrWdStart1;
        this.effectiveDate = effectiveDate;
        this.createAt = createAt;
        this.modifyAt = modifyAt;
        this.modifyBy = modifyBy;
    }
    public Office(String officeId, String engRegion, String chtRegion, String chsRegion, String engDistrict, String chtDistrict, String chsDistrict, String engAddr, String chtAddr, String chsAddr, String engAddrHint, String chtAddrHint, String chsAddrHint, String engOffName, String chtOffName, String chsOffName, String telNum, String faxNum, String image, BigDecimal latitude, BigDecimal longitude, String engAddrUrl, String chtAddrUrl, String chsAddrUrl, String offHrWdStart1, String offHrWdEnd1, String offHrWdStart2, String offHrWdEnd2, String offHrSatStart1, String offHrSatEnd1, String offHrSatStart2, String offHrSatEnd2, String offHrSunStart1, String offHrSunEnd1, String offHrSunStart2, String offHrSunEnd2, String engOffHrWdNote, String engOffHrSatNote, String engOffHrSunNote, String chtOffHrWdNote, String chtOffHrSatNote, String chtOffHrSunNote, String chsOffHrWdNote, String chsOffHrSatNote, String chsOffHrSunNote, Date effectiveDate, Date createAt, Date modifyAt, String modifyBy) {
       this.officeId = officeId;
       this.engRegion = engRegion;
       this.chtRegion = chtRegion;
       this.chsRegion = chsRegion;
       this.engDistrict = engDistrict;
       this.chtDistrict = chtDistrict;
       this.chsDistrict = chsDistrict;
       this.engAddr = engAddr;
       this.chtAddr = chtAddr;
       this.chsAddr = chsAddr;
       this.engAddrHint = engAddrHint;
       this.chtAddrHint = chtAddrHint;
       this.chsAddrHint = chsAddrHint;
       this.engOffName = engOffName;
       this.chtOffName = chtOffName;
       this.chsOffName = chsOffName;
       this.telNum = telNum;
       this.faxNum = faxNum;
       this.image = image;
       this.latitude = latitude;
       this.longitude = longitude;
       this.engAddrUrl = engAddrUrl;
       this.chtAddrUrl = chtAddrUrl;
       this.chsAddrUrl = chsAddrUrl;
       this.offHrWdStart1 = offHrWdStart1;
       this.offHrWdEnd1 = offHrWdEnd1;
       this.offHrWdStart2 = offHrWdStart2;
       this.offHrWdEnd2 = offHrWdEnd2;
       this.offHrSatStart1 = offHrSatStart1;
       this.offHrSatEnd1 = offHrSatEnd1;
       this.offHrSatStart2 = offHrSatStart2;
       this.offHrSatEnd2 = offHrSatEnd2;
       this.offHrSunStart1 = offHrSunStart1;
       this.offHrSunEnd1 = offHrSunEnd1;
       this.offHrSunStart2 = offHrSunStart2;
       this.offHrSunEnd2 = offHrSunEnd2;
       this.engOffHrWdNote = engOffHrWdNote;
       this.engOffHrSatNote = engOffHrSatNote;
       this.engOffHrSunNote = engOffHrSunNote;
       this.chtOffHrWdNote = chtOffHrWdNote;
       this.chtOffHrSatNote = chtOffHrSatNote;
       this.chtOffHrSunNote = chtOffHrSunNote;
       this.chsOffHrWdNote = chsOffHrWdNote;
       this.chsOffHrSatNote = chsOffHrSatNote;
       this.chsOffHrSunNote = chsOffHrSunNote;
       this.effectiveDate = effectiveDate;
       this.createAt = createAt;
       this.modifyAt = modifyAt;
       this.modifyBy = modifyBy;
    }
   
     @Id 

    
    @Column(name="OFFICE_ID", unique=true, nullable=false, length=10)
    public String getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    
    @Column(name="ENG_REGION", nullable=false, length=30)
    public String getEngRegion() {
        return this.engRegion;
    }
    
    public void setEngRegion(String engRegion) {
        this.engRegion = engRegion;
    }

    
    @Column(name="CHT_REGION", nullable=false, length=30)
    public String getChtRegion() {
        return this.chtRegion;
    }
    
    public void setChtRegion(String chtRegion) {
        this.chtRegion = chtRegion;
    }

    
    @Column(name="CHS_REGION", nullable=false, length=30)
    public String getChsRegion() {
        return this.chsRegion;
    }
    
    public void setChsRegion(String chsRegion) {
        this.chsRegion = chsRegion;
    }

    
    @Column(name="ENG_DISTRICT", nullable=false, length=30)
    public String getEngDistrict() {
        return this.engDistrict;
    }
    
    public void setEngDistrict(String engDistrict) {
        this.engDistrict = engDistrict;
    }

    
    @Column(name="CHT_DISTRICT", nullable=false, length=30)
    public String getChtDistrict() {
        return this.chtDistrict;
    }
    
    public void setChtDistrict(String chtDistrict) {
        this.chtDistrict = chtDistrict;
    }

    
    @Column(name="CHS_DISTRICT", nullable=false, length=30)
    public String getChsDistrict() {
        return this.chsDistrict;
    }
    
    public void setChsDistrict(String chsDistrict) {
        this.chsDistrict = chsDistrict;
    }

    
    @Column(name="ENG_ADDR", nullable=false, length=2000)
    public String getEngAddr() {
        return this.engAddr;
    }
    
    public void setEngAddr(String engAddr) {
        this.engAddr = engAddr;
    }

    
    @Column(name="CHT_ADDR", nullable=false, length=2000)
    public String getChtAddr() {
        return this.chtAddr;
    }
    
    public void setChtAddr(String chtAddr) {
        this.chtAddr = chtAddr;
    }

    
    @Column(name="CHS_ADDR", nullable=false, length=2000)
    public String getChsAddr() {
        return this.chsAddr;
    }
    
    public void setChsAddr(String chsAddr) {
        this.chsAddr = chsAddr;
    }

    
    @Column(name="ENG_ADDR_HINT", length=100)
    public String getEngAddrHint() {
        return this.engAddrHint;
    }
    
    public void setEngAddrHint(String engAddrHint) {
        this.engAddrHint = engAddrHint;
    }

    
    @Column(name="CHT_ADDR_HINT", length=50)
    public String getChtAddrHint() {
        return this.chtAddrHint;
    }
    
    public void setChtAddrHint(String chtAddrHint) {
        this.chtAddrHint = chtAddrHint;
    }

    
    @Column(name="CHS_ADDR_HINT", length=50)
    public String getChsAddrHint() {
        return this.chsAddrHint;
    }
    
    public void setChsAddrHint(String chsAddrHint) {
        this.chsAddrHint = chsAddrHint;
    }

    
    @Column(name="ENG_OFF_NAME", nullable=false, length=100)
    public String getEngOffName() {
        return this.engOffName;
    }
    
    public void setEngOffName(String engOffName) {
        this.engOffName = engOffName;
    }

    
    @Column(name="CHT_OFF_NAME", nullable=false, length=25)
    public String getChtOffName() {
        return this.chtOffName;
    }
    
    public void setChtOffName(String chtOffName) {
        this.chtOffName = chtOffName;
    }

    
    @Column(name="CHS_OFF_NAME", nullable=false, length=25)
    public String getChsOffName() {
        return this.chsOffName;
    }
    
    public void setChsOffName(String chsOffName) {
        this.chsOffName = chsOffName;
    }

    
    @Column(name="TEL_NUM", nullable=false, length=15)
    public String getTelNum() {
        return this.telNum;
    }
    
    public void setTelNum(String telNum) {
        this.telNum = telNum;
    }

    
    @Column(name="FAX_NUM", length=15)
    public String getFaxNum() {
        return this.faxNum;
    }
    
    public void setFaxNum(String faxNum) {
        this.faxNum = faxNum;
    }

    
    @Column(name="IMAGE", nullable=false, length=256)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="LATITUDE", nullable=false, precision=3, scale=6)
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="LONGITUDE", nullable=false, precision=3, scale=6)
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="ENG_ADDR_URL", nullable=false, length=256)
    public String getEngAddrUrl() {
        return this.engAddrUrl;
    }
    
    public void setEngAddrUrl(String engAddrUrl) {
        this.engAddrUrl = engAddrUrl;
    }

    
    @Column(name="CHT_ADDR_URL", nullable=false, length=256)
    public String getChtAddrUrl() {
        return this.chtAddrUrl;
    }
    
    public void setChtAddrUrl(String chtAddrUrl) {
        this.chtAddrUrl = chtAddrUrl;
    }

    
    @Column(name="CHS_ADDR_URL", nullable=false, length=256)
    public String getChsAddrUrl() {
        return this.chsAddrUrl;
    }
    
    public void setChsAddrUrl(String chsAddrUrl) {
        this.chsAddrUrl = chsAddrUrl;
    }

    
    @Column(name="OFF_HR_WD_START1", nullable=false, length=4)
    public String getOffHrWdStart1() {
        return this.offHrWdStart1;
    }
    
    public void setOffHrWdStart1(String offHrWdStart1) {
        this.offHrWdStart1 = offHrWdStart1;
    }

    
    @Column(name="OFF_HR_WD_END1", length=4)
    public String getOffHrWdEnd1() {
        return this.offHrWdEnd1;
    }
    
    public void setOffHrWdEnd1(String offHrWdEnd1) {
        this.offHrWdEnd1 = offHrWdEnd1;
    }

    
    @Column(name="OFF_HR_WD_START2", length=4)
    public String getOffHrWdStart2() {
        return this.offHrWdStart2;
    }
    
    public void setOffHrWdStart2(String offHrWdStart2) {
        this.offHrWdStart2 = offHrWdStart2;
    }

    
    @Column(name="OFF_HR_WD_END2", length=4)
    public String getOffHrWdEnd2() {
        return this.offHrWdEnd2;
    }
    
    public void setOffHrWdEnd2(String offHrWdEnd2) {
        this.offHrWdEnd2 = offHrWdEnd2;
    }

    
    @Column(name="OFF_HR_SAT_START1", length=4)
    public String getOffHrSatStart1() {
        return this.offHrSatStart1;
    }
    
    public void setOffHrSatStart1(String offHrSatStart1) {
        this.offHrSatStart1 = offHrSatStart1;
    }

    
    @Column(name="OFF_HR_SAT_END1", length=4)
    public String getOffHrSatEnd1() {
        return this.offHrSatEnd1;
    }
    
    public void setOffHrSatEnd1(String offHrSatEnd1) {
        this.offHrSatEnd1 = offHrSatEnd1;
    }

    
    @Column(name="OFF_HR_SAT_START2", length=4)
    public String getOffHrSatStart2() {
        return this.offHrSatStart2;
    }
    
    public void setOffHrSatStart2(String offHrSatStart2) {
        this.offHrSatStart2 = offHrSatStart2;
    }

    
    @Column(name="OFF_HR_SAT_END2", length=4)
    public String getOffHrSatEnd2() {
        return this.offHrSatEnd2;
    }
    
    public void setOffHrSatEnd2(String offHrSatEnd2) {
        this.offHrSatEnd2 = offHrSatEnd2;
    }

    
    @Column(name="OFF_HR_SUN_START1", length=4)
    public String getOffHrSunStart1() {
        return this.offHrSunStart1;
    }
    
    public void setOffHrSunStart1(String offHrSunStart1) {
        this.offHrSunStart1 = offHrSunStart1;
    }

    
    @Column(name="OFF_HR_SUN_END1", length=4)
    public String getOffHrSunEnd1() {
        return this.offHrSunEnd1;
    }
    
    public void setOffHrSunEnd1(String offHrSunEnd1) {
        this.offHrSunEnd1 = offHrSunEnd1;
    }

    
    @Column(name="OFF_HR_SUN_START2", length=4)
    public String getOffHrSunStart2() {
        return this.offHrSunStart2;
    }
    
    public void setOffHrSunStart2(String offHrSunStart2) {
        this.offHrSunStart2 = offHrSunStart2;
    }

    
    @Column(name="OFF_HR_SUN_END2", length=4)
    public String getOffHrSunEnd2() {
        return this.offHrSunEnd2;
    }
    
    public void setOffHrSunEnd2(String offHrSunEnd2) {
        this.offHrSunEnd2 = offHrSunEnd2;
    }

    
    @Column(name="ENG_OFF_HR_WD_NOTE", length=100)
    public String getEngOffHrWdNote() {
        return this.engOffHrWdNote;
    }
    
    public void setEngOffHrWdNote(String engOffHrWdNote) {
        this.engOffHrWdNote = engOffHrWdNote;
    }

    
    @Column(name="ENG_OFF_HR_SAT_NOTE", length=100)
    public String getEngOffHrSatNote() {
        return this.engOffHrSatNote;
    }
    
    public void setEngOffHrSatNote(String engOffHrSatNote) {
        this.engOffHrSatNote = engOffHrSatNote;
    }

    
    @Column(name="ENG_OFF_HR_SUN_NOTE", length=100)
    public String getEngOffHrSunNote() {
        return this.engOffHrSunNote;
    }
    
    public void setEngOffHrSunNote(String engOffHrSunNote) {
        this.engOffHrSunNote = engOffHrSunNote;
    }

    
    @Column(name="CHT_OFF_HR_WD_NOTE", length=100)
    public String getChtOffHrWdNote() {
        return this.chtOffHrWdNote;
    }
    
    public void setChtOffHrWdNote(String chtOffHrWdNote) {
        this.chtOffHrWdNote = chtOffHrWdNote;
    }

    
    @Column(name="CHT_OFF_HR_SAT_NOTE", length=100)
    public String getChtOffHrSatNote() {
        return this.chtOffHrSatNote;
    }
    
    public void setChtOffHrSatNote(String chtOffHrSatNote) {
        this.chtOffHrSatNote = chtOffHrSatNote;
    }

    
    @Column(name="CHT_OFF_HR_SUN_NOTE", length=100)
    public String getChtOffHrSunNote() {
        return this.chtOffHrSunNote;
    }
    
    public void setChtOffHrSunNote(String chtOffHrSunNote) {
        this.chtOffHrSunNote = chtOffHrSunNote;
    }

    
    @Column(name="CHS_OFF_HR_WD_NOTE", length=100)
    public String getChsOffHrWdNote() {
        return this.chsOffHrWdNote;
    }
    
    public void setChsOffHrWdNote(String chsOffHrWdNote) {
        this.chsOffHrWdNote = chsOffHrWdNote;
    }

    
    @Column(name="CHS_OFF_HR_SAT_NOTE", length=100)
    public String getChsOffHrSatNote() {
        return this.chsOffHrSatNote;
    }
    
    public void setChsOffHrSatNote(String chsOffHrSatNote) {
        this.chsOffHrSatNote = chsOffHrSatNote;
    }

    
    @Column(name="CHS_OFF_HR_SUN_NOTE", length=100)
    public String getChsOffHrSunNote() {
        return this.chsOffHrSunNote;
    }
    
    public void setChsOffHrSunNote(String chsOffHrSunNote) {
        this.chsOffHrSunNote = chsOffHrSunNote;
    }

    
    @Column(name="EFFECTIVE_DATE", nullable=false)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    
    @Column(name="CREATE_AT", nullable=false)
    public Date getCreateAt() {
        return this.createAt;
    }
    
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    
    @Column(name="MODIFY_AT", nullable=false)
    public Date getModifyAt() {
        return this.modifyAt;
    }
    
    public void setModifyAt(Date modifyAt) {
        this.modifyAt = modifyAt;
    }

    
    @Column(name="MODIFY_BY", nullable=false, length=3)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }




}


