package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 26, 2018 2:31:07 PM by Hibernate Tools 5.0.6.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuotaPlan generated by hbm2java
 */
@Entity
@Table(name="QUOTA_PLAN"
)
public class QuotaPlan  implements Serializable {


     private BigDecimal quotaId;
     private String apptType;
     private Date apptDate;
     private String officeId;
     private byte interval;
     private String startTime;
     private String endTime;
     private BigDecimal totalQuota;
     private BigDecimal avaQuota;
     private BigDecimal usedQuota;
     private BigDecimal freezeQuota;
     private BigDecimal virQuotaUsed;
     private Date createDate;
     private String createBy;
     private Date lastUpdDate;
     private String lastUpdBy;

    public QuotaPlan() {
    }

    public QuotaPlan(BigDecimal quotaId, String apptType, Date apptDate, String officeId, byte interval, String startTime, String endTime, BigDecimal totalQuota, BigDecimal avaQuota, BigDecimal usedQuota, BigDecimal freezeQuota, BigDecimal virQuotaUsed, Date createDate, String createBy, Date lastUpdDate, String lastUpdBy) {
       this.quotaId = quotaId;
       this.apptType = apptType;
       this.apptDate = apptDate;
       this.officeId = officeId;
       this.interval = interval;
       this.startTime = startTime;
       this.endTime = endTime;
       this.totalQuota = totalQuota;
       this.avaQuota = avaQuota;
       this.usedQuota = usedQuota;
       this.freezeQuota = freezeQuota;
       this.virQuotaUsed = virQuotaUsed;
       this.createDate = createDate;
       this.createBy = createBy;
       this.lastUpdDate = lastUpdDate;
       this.lastUpdBy = lastUpdBy;
    }
   
     @Id 

    
    @Column(name="QUOTA_ID", unique=true, nullable=false, precision=38, scale=0)
    public BigDecimal getQuotaId() {
        return this.quotaId;
    }
    
    public void setQuotaId(BigDecimal quotaId) {
        this.quotaId = quotaId;
    }

    
    @Column(name="APPT_TYPE", nullable=false, length=1)
    public String getApptType() {
        return this.apptType;
    }
    
    public void setApptType(String apptType) {
        this.apptType = apptType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APPT_DATE", nullable=false, length=7)
    public Date getApptDate() {
        return this.apptDate;
    }
    
    public void setApptDate(Date apptDate) {
        this.apptDate = apptDate;
    }

    
    @Column(name="OFFICE_ID", nullable=false, length=10)
    public String getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    
    @Column(name="INTERVAL", nullable=false, precision=2, scale=0)
    public byte getInterval() {
        return this.interval;
    }
    
    public void setInterval(byte interval) {
        this.interval = interval;
    }

    
    @Column(name="START_TIME", nullable=false, length=4)
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="END_TIME", nullable=false, length=4)
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="TOTAL_QUOTA", nullable=false, precision=38, scale=0)
    public BigDecimal getTotalQuota() {
        return this.totalQuota;
    }
    
    public void setTotalQuota(BigDecimal totalQuota) {
        this.totalQuota = totalQuota;
    }

    
    @Column(name="AVA_QUOTA", nullable=false, precision=38, scale=0)
    public BigDecimal getAvaQuota() {
        return this.avaQuota;
    }
    
    public void setAvaQuota(BigDecimal avaQuota) {
        this.avaQuota = avaQuota;
    }

    
    @Column(name="USED_QUOTA", nullable=false, precision=38, scale=0)
    public BigDecimal getUsedQuota() {
        return this.usedQuota;
    }
    
    public void setUsedQuota(BigDecimal usedQuota) {
        this.usedQuota = usedQuota;
    }

    
    @Column(name="FREEZE_QUOTA", nullable=false, precision=38, scale=0)
    public BigDecimal getFreezeQuota() {
        return this.freezeQuota;
    }
    
    public void setFreezeQuota(BigDecimal freezeQuota) {
        this.freezeQuota = freezeQuota;
    }

    
    @Column(name="VIR_QUOTA_USED", nullable=false, precision=38, scale=0)
    public BigDecimal getVirQuotaUsed() {
        return this.virQuotaUsed;
    }
    
    public void setVirQuotaUsed(BigDecimal virQuotaUsed) {
        this.virQuotaUsed = virQuotaUsed;
    }

    
    @Column(name="CREATE_DATE", nullable=false)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_BY", nullable=false, length=3)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="LAST_UPD_DATE", nullable=false)
    public Date getLastUpdDate() {
        return this.lastUpdDate;
    }
    
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    
    @Column(name="LAST_UPD_BY", nullable=false, length=3)
    public String getLastUpdBy() {
        return this.lastUpdBy;
    }
    
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }




}


