package com.pccw.immd.adminfunc.smartics2.domain;
// Generated May 23, 2018 11:46:55 AM by Hibernate Tools 5.0.6.Final


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmApplicationId generated by hbm2java
 */
@Entity
@Table(name="UM_APPLICATION_ID"
)
public class UmApplicationId  implements Serializable {


     private String appId;
     private Date createAt;
     private Date modifyAt;
     private String modifyBy;
     private String engAppName;
     private String chtAppName;
     private String chsAppName;
     private String requireReminder;
     private Short reminderDay;
     private Date effectiveDate;
     private String updateFlag;
     private String actionType;

    public UmApplicationId() {
    }

	
    public UmApplicationId(String appId) {
        this.appId = appId;
    }
    public UmApplicationId(String appId, Date createAt, Date modifyAt, String modifyBy, String engAppName, String chtAppName, String chsAppName, String requireReminder, Short reminderDay, Date effectiveDate, String updateFlag, String actionType) {
       this.appId = appId;
       this.createAt = createAt;
       this.modifyAt = modifyAt;
       this.modifyBy = modifyBy;
       this.engAppName = engAppName;
       this.chtAppName = chtAppName;
       this.chsAppName = chsAppName;
       this.requireReminder = requireReminder;
       this.reminderDay = reminderDay;
       this.effectiveDate = effectiveDate;
       this.updateFlag = updateFlag;
       this.actionType = actionType;
    }
   
     @Id 

    
    @Column(name="APP_ID", unique=true, nullable=false, length=4)
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_AT")
    public Date getCreateAt() {
        return this.createAt;
    }
    
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_AT")
    public Date getModifyAt() {
        return this.modifyAt;
    }
    
    public void setModifyAt(Date modifyAt) {
        this.modifyAt = modifyAt;
    }

    
    @Column(name="MODIFY_BY", length=1)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    
    @Column(name="ENG_APP_NAME", length=480)
    public String getEngAppName() {
        return this.engAppName;
    }
    
    public void setEngAppName(String engAppName) {
        this.engAppName = engAppName;
    }

    
    @Column(name="CHT_APP_NAME", length=200)
    public String getChtAppName() {
        return this.chtAppName;
    }
    
    public void setChtAppName(String chtAppName) {
        this.chtAppName = chtAppName;
    }

    
    @Column(name="CHS_APP_NAME", length=200)
    public String getChsAppName() {
        return this.chsAppName;
    }
    
    public void setChsAppName(String chsAppName) {
        this.chsAppName = chsAppName;
    }

    
    @Column(name="REQUIRE_REMINDER", length=1)
    public String getRequireReminder() {
        return this.requireReminder;
    }
    
    public void setRequireReminder(String requireReminder) {
        this.requireReminder = requireReminder;
    }

    
    @Column(name="REMINDER_DAY", precision=3, scale=0)
    public Short getReminderDay() {
        return this.reminderDay;
    }
    
    public void setReminderDay(Short reminderDay) {
        this.reminderDay = reminderDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    
    @Column(name="UPDATE_FLAG", length=1)
    public String getUpdateFlag() {
        return this.updateFlag;
    }
    
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    
    @Column(name="ACTION_TYPE", length=10)
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }




}


